### ISSUE TITLE
Format Files

### ISSUE THREAD

**Issue by KendallDoesCoding** [sakshgupta/Windows-11-Site#1]
I think the files should be organized and formatted within folders, just so it looks a little neat.... I can do this if you need.

btw amazing site.

**Comment by sakshgupta** [comment]
I know 😅, It was just for practice so I just made it like that, I should have did it earlier only, if you want to do it you can else I'll do it. 
Thank you.

**Comment by KendallDoesCoding** [comment]
> I know 😅, It was just for practice so I just made it like that, I should have did it earlier only, if you want to do it you can else I'll do it. Thank you.

No problem! Yeah, I'll try doing it... Thanks.
